---
name: "pre-release"

on: [push]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-release-docker:
    name: "Pre Release Docker"
    runs-on: "ubuntu-latest"
    steps:
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=long
          type=sha
          type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=ref,event=tag
          type=ref,event=branch

    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: "${{ secrets.DOCKER_HUB_USER }}"
        password: "${{ secrets.DOCKER_HUB_TOKEN }}"
    - name: "Build and push docker image"
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
